name: JSMStat
options:
  bundleIdPrefix: com.jsmstat
  deploymentTarget:
    macOS: "26.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "6.0"
    MACOSX_DEPLOYMENT_TARGET: "26.0"
    SWIFT_STRICT_CONCURRENCY: "targeted"
targets:
  JSMStat:
    type: application
    platform: macOS
    sources:
      - path: JSMStat
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jsmstat.app
        PRODUCT_NAME: JSMStat
        INFOPLIST_FILE: JSMStat/Info.plist
        CODE_SIGN_ENTITLEMENTS: JSMStat/JSMStat.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        GENERATE_INFOPLIST_FILE: false
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: 1
        COMBINE_HIDPI_IMAGES: true
    entitlements:
      path: JSMStat/JSMStat.entitlements
  JSMStatTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: JSMStatTests
    dependencies:
      - target: JSMStat
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jsmstat.tests
        GENERATE_INFOPLIST_FILE: true
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/JSMStat.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/JSMStat"
        BUNDLE_LOADER: "$(TEST_HOST)"
